### ISSUE TITLE
Migrate to go-libp2p-core

### ISSUE THREAD

**Issue by backkem** [libp2p/go-libp2p-webrtc-direct#31]
go-libp2p-core now holds the main interfaces and abstractions that make up go-libp2p, see libp2p/go-libp2p#602. We should use it to reduce the dependency graph.

**Comment by Jukie** [comment]
I'd love to help out, how would I properly test my changes? Could you possibly add some contribution docs?

**Comment by backkem** [comment]
Hi @Jukie, would love to have you. The package tests run a rather extensive test suite. So, just running `go test` should give you a good indication.

**Comment by Jukie** [comment]
Awesome, thanks for the info!

**Comment by raulk** [comment]
I missed migrating this one! Could you send a PR to get this repo added to the libp2p/workspace-go-libp2p repo?

**Comment by backkem** [comment]
@raulk I tried to add the submodule to libp2p/workspace-go-libp2p but I don't have the rights to push to this repo.

**Comment by raulk** [comment]
@backkem sent you an invite

**Comment by backkem** [comment]
Fixed by #30
